backend:
    name: test-repo

media_folder: static/assets
public_folder: assets

collections:
    - name: category
      label: Category
      folder: categories
      create: true
      fields:
        - { name: title, label: Title }
        - { name: hasCustom, label: "Custom Option Available", widget: boolean, required: false }
    - name: product
      label: Product
      folder: products
      create: true
      fields:
        - { name: title, label: Title }
        - { name: sku, label: SKU }
        - { name: price, label: Price, widget: number }
        - { name: category, label: Category, widget: relation, collection: category, searchFields: ["name"], valueField: name }
        - { name: thumbnail, label: Image, widget: image }
        - { name: description, label: Description, widget: text }
        - { name: tags, label: Tags, widget: list }
