backend:
    name: github
    repo: teletypist/think-gatsbyjs-cms-starter

media_folder: static/assets
public_folder: assets

collections:
    - name: category
      label: Category
      folder: src/pages/categories
      create: true
      fields:
        - { name: title, label: Title }
        - { name: hasCustom, label: "Custom Option Available", widget: boolean, required: false }
    - name: product
      label: Product
      folder: src/pages/products
      create: true
      fields:
        - { name: sku, label: SKU }
        - { name: category, label: Category, widget: relation, collection: category, searchFields: ["title"], valueField: title }
        - label: Variants
          name: variants
          widget: list
          fields:
            - { name: name, label: Name }
            - { name: price, label: "Price (cents)", widget: number }
            - { name: thumbnail, label: Thumbnail, widget: image, required: false }
        - { name: feature, label: "Feature Image", widget: image, required: false }
        - { name: description, label: Description, widget: text, required: false }
        - { name: tags, label: Tags, widget: list, required: false }
